language: node_js

sudo: false


# the matrix allows you to specify different operating systems and environments to
# run your tests and build binaries
matrix:
  include:
    # linux publishable node v8
    - os: linux
      env: BUILDTYPE=release
      node_js: 8
#deploy:
  #provider: pages
  #skip-cleanup: true
  #github-token: $GH_TOKEN # github 上的token环境变量
  #local-dir: ./_MYOUTPUT/ ## 根据情况自定义到静态文件输出目录
  #target-branch: gh-pages
  #verbose: true
  #on:
    #branch: master
before_script:
  - npm install
  - npm install -g gulp
  - npm run build
  #- ls -a
  #- rm -rf .git --如果推送整个目录则需要删除.git文件，如果只推送构建后的文件目录dist则cd ./dist就行，不需要删除.git文件，否则最后一句git push会推送不上
  #- ls -a
  #- git init
  #- git config user.name "${U_NAME}"
  #- git config user.email "${U_EMAIL}"
  #- git add .
  #- git commit -m "commit 111"
  #- git status
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:dev
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKENS  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
